### PR TITLE
FitsImage get()

### PR DESCRIPTION
**Pull request by austinbeauch**

### CODE REVIEW

**Review by mtbannister — CHANGES_REQUESTED** [review]
CUTOUT_RADIUS needs a line of documentation explaining its value. e.g. the 60.0 implies arcseconds: this should be made explicit.
Similarly, the doclines in cutout (532-534) should explain in much more detail, with examples, if the cutout size is to refer to pixel values, to WCS (i.e. RA/Dec) values, or to single CCDs of the mosaic.

Line 616-618: CUTOUT_RADIUS should be exposed as a variable and documented as such in ra_dec_cutout. The chosen default is appropriate.
The docstrings for ra_dec_cutout also need to specify that RA is to be given in degrees, as this is unusual (though not uncommon) for astronomers.

**Comment by austinbeauch** [comment]
@mtbannister for the documentation on lines 532, can the cutout refer to 3 different things? From my understanding there are only two: the "pixel level" and WCS. As per an old email from JJ, "If that string is enclosed in square brackets then the cutout action is at the pixel level. If the string is enclosed in round brackets then the action is at the World Coordinate (RA/Dec) level."
Is there another input in square brackets that is not a CCD?

**Comment by mtbannister** [comment]
Hmm, I think my confusion is that it is possible to return three parts of a FITS image from VOSpace:
- a whole CCD, indexed by the CCD number (via the square bracket syntax)
- a pixel cutout of a given CCD
- a WCS.

See also https://github.com/OSSOS/MOP/blob/master/src/ossos/core/ossos/tools/postage_stamp_builder.py 
for a different approach.

**Comment by austinbeauch** [comment]
@ijiraq What format would be required for the cutout method to return a pixel selection from a CCD?

**Comment by ijiraq** [comment]
[CCD][x1:x2,y1:y2]

JJ

**Comment by austinbeauch** [comment]
In ra_dec_cutout the skycoord object isn't given in degrees directly, but as an astropy SkyCoord object. I added a bit of clarification. 
Let me know if any of it needs to be changed.

**Comment by ijiraq** [comment]
I think radius parameter should be passed around as an astropy.quantity object. Then the units are in the variable and confusion goes down. When the call to copy happens, with the string for cutout, then the method can access the value in degrees using the 'to' attribute of a quantity.

**Comment by austinbeauch** [comment]
With the units being set to degrees? So in ra_dec_cutout I can add the line 
`radius = units.Quantity(radius, unit='degree')`
and then change the rest accordingly. This takes the input argument which is a float/int and converts it to  an astropy quantity object.

**Comment by ijiraq** [comment]
I think the caller of ra_dec_cutout is where one sets radius to a quantity.  The expectation is that when ra_dec_cutout is called the value in 'radius' is a quantity object.  So callers of ra_dec_cutout would be required to send it a quantity.   Later when ra_dec_cutout builds the 'cutout' string then the value is pulled in degrees.  The constant you are using for the default value of radius parameter CUTOUT_RADIUS would then need to be a quantity.   Also, ra_dec_cutout will need to have a check to ensure that a quantity is being passed in rather than a float.   Perhaps the condition could be that if the value is a float then we can assume degrees?

**Comment by austinbeauch** [comment]
Doing some unit testing now that there's more error checking for types, would you rather I follow PEP8 conventions for when lines get too long or just leave them as long single lines? PyCharm's indentation looks a little weird on some lines, nothing too wacky though.

**Comment by ijiraq** [comment]
please follow PEP8.

JJ

**Comment by austinbeauch** [comment]
If the input is a float it gets converted to a Quantity object in degrees. Also I added a single spacing line on line 57 to separate the comment explaining CUTOUT_RADIUS, I could remove it if you want all the global variable to be defined completely together.

**Review by mtbannister — APPROVED** [review]

**Pull request merged**
